### ISSUE TITLE
version 1.2.0 broke the import of the prime Aura theme

### ISSUE THREAD

**Issue by ronan-connolly** [primefaces/primeuix#135]
Breaks: "@primeuix/themes": "1.2.0",
Works: "@primeuix/themes": "1.1.2",

Following this guide:
https://primeng.org/installation

The import does not work with the 1.20 or later version:
`import Aura from '@primeuix/themes/aura';` 

My details:
- Latest NX Monorepo version (v21), and Angular (v20).
- Apple Silicon 

Error:
```yaml
  ✘ [ERROR] TS2307: Cannot find module '@primeuix/themes/aura' or its correspondi    ║
  ng type declarations. [plugin angular-compiler]                                    ║
                                                                                     ║
      apps/my-app/src/app/app.config.ts:29:17:                                        ║
        29 │ import Aura from '@primeuix/themes/aura';       
```

**Comment by Wiemarp** [comment]
@mertsincan Thank you, that fixed the issue. When running `npx nx migrate --run-migrations=migrations.json` using Nx `21.5.3` it didn't update my moduleResolution to bundler like it supposed to. Thanks for the help.

**Comment by mertsincan** [comment]
Glad to hear, thanks a lot for your update!
